image: python:3.10.4

stages:
  - linting
  - testing
  - building

before_script:
  - apt-get update
  - apt install -y libldap2-dev libsasl2-dev ldap-utils
  - pip install --upgrade pip && pip install -r requirements.txt

imports ordering:
  stage: linting
  interruptible: true
  except:
    refs:
      - schedules
    changes:
      - "**/README.md"
      - "cate-proxy-db/*"

  script:
    - isort *.py {app,tests}/**/*.py --check-only

style checks:
  stage: linting
  interruptible: true
  except:
    refs:
      - schedules
    changes:
      - "**/README.md"
      - "cate-proxy-db/*"
  script:
    - flake8 .

type checks:
  stage: linting
  interruptible: true
  except:
    refs:
      - schedules
    changes:
      - "**/README.md"
      - "cate-proxy-db/*"
  script:
    - mypy .

unit_test:
  stage: testing
  interruptible: true
  except:
    refs:
      - schedules
    changes:
      - "**/README.md"
      - "cate-proxy-db/*"
  services:
    - name: postgres
      alias: db-service
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    POSTGRES_USER: "user"
    POSTGRES_PASSWORD: "pass"
    TEST_DB_SERVER_URL: "postgresql://user:pass@db-service"
  cache:
    key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
    paths:
      - .cache/pip
  script:
    - pytest --junitxml=report.xml --cov=app/ --cov-report term-missing tests/
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
