default_language_version:
  python: python3

repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [ --profile, black ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: debug-statements
  - repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [ --recursive, --exclude, tests ]

# Commenting this out for the moment due to the unexpected issue
# with this mirror repository of mypy, which fails with sqlmodel.SQLModel
# with the following error:
#   Unexpected keyword argument "table" for "__init_subclass__" of "object"
# There may be ground to file an issue on the repo.
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.942
#    hooks:
#      - id: mypy
#        additional_dependencies: [types-requests==2.27.16]
