default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: debug-statements
  - repo: https://github.com/ambv/black
    rev: 24.1.1
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        args: [ --recursive, --exclude, tests, --skip, "B404,B602,B603,B607" ]
