"""Add new columns and constraints to personal tutoring table

Revision ID: 1b97ea293774
Revises: e5dde5f23626
Create Date: 2023-09-07 11:20:38.018838

"""
import sqlalchemy as sa
import sqlmodel  # added
from alembic import op

# revision identifiers, used by Alembic.
revision = "1b97ea293774"
down_revision = "e5dde5f23626"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "personal_tutoring_meeting", sa.Column("updated", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "personal_tutoring_meeting",
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("personal_tutoring_meeting", "updated_by")
    op.drop_column("personal_tutoring_meeting", "updated")
    # ### end Alembic commands ###
