"""Link external_module_on_offer to external_module_choice

Revision ID: 2c46654e82f6
Revises: c6ede63a2345
Create Date: 2024-03-06 11:48:28.610844

"""
import sqlalchemy as sa
import sqlmodel  # added
from alembic import op

# revision identifiers, used by Alembic.
revision = "2c46654e82f6"
down_revision = "c6ede63a2345"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "external_module_choice",
        sa.Column("external_module_id", sa.Integer(), nullable=False),
    )
    op.drop_constraint(
        "external_module_choice_year_module_code_username_key",
        "external_module_choice",
        type_="unique",
    )
    op.create_index(
        op.f("ix_external_module_choice_external_module_id"),
        "external_module_choice",
        ["external_module_id"],
        unique=False,
    )
    op.create_unique_constraint(
        None, "external_module_choice", ["external_module_id", "username"]
    )
    op.create_foreign_key(
        None,
        "external_module_choice",
        "external_module_on_offer",
        ["external_module_id"],
        ["id"],
    )
    op.drop_column("external_module_choice", "year")
    op.drop_column("external_module_choice", "module_code")
    op.add_column(
        "external_module_on_offer",
        sa.Column("year", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("external_module_on_offer", "year")
    op.add_column(
        "external_module_choice",
        sa.Column("module_code", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "external_module_choice",
        sa.Column("year", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "external_module_choice", type_="foreignkey")
    op.drop_constraint(None, "external_module_choice", type_="unique")
    op.drop_index(
        op.f("ix_external_module_choice_external_module_id"),
        table_name="external_module_choice",
    )
    op.create_unique_constraint(
        "external_module_choice_year_module_code_username_key",
        "external_module_choice",
        ["year", "module_code", "username"],
    )
    op.drop_column("external_module_choice", "external_module_id")
    # ### end Alembic commands ###
