"""Add offering_group_constraint table

Revision ID: 42af62166d24
Revises: bcf82183391a
Create Date: 2024-03-22 15:41:30.000875

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "42af62166d24"
down_revision = "bcf82183391a"
branch_labels = None
depends_on = None


def upgrade():
    offering_group_enum = sa.Enum(
        "OPTIONAL", "SELECTIVE", name="offering_group", create_type=False
    )
    op.create_table(
        "offering_group_constraint",
        sa.Column("offering_group", offering_group_enum, nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("min", sa.Integer(), nullable=False),
        sa.Column("max", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("offering_group_constraint")
    # ### end Alembic commands ###
