"""Update personal_tutor_meeting table

Revision ID: 6a924c60b70a
Revises: 1b97ea293774
Create Date: 2023-10-04 16:18:27.076378

"""
import sqlalchemy as sa
import sqlmodel  # added
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6a924c60b70a"
down_revision = "1b97ea293774"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "personal_tutoring_meeting",
        sa.Column("tutee", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "personal_tutoring_meeting",
        sa.Column("tutor", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "personal_tutoring_meeting",
        sa.Column(
            "timestamp",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
        ),
    )
    op.drop_column("personal_tutoring_meeting", "tutee_login")
    op.drop_column("personal_tutoring_meeting", "updated")
    op.drop_column("personal_tutoring_meeting", "tutor_login")
    op.drop_column("personal_tutoring_meeting", "updated_by")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "personal_tutoring_meeting",
        sa.Column("updated_by", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "personal_tutoring_meeting",
        sa.Column("tutor_login", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "personal_tutoring_meeting",
        sa.Column(
            "updated", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "personal_tutoring_meeting",
        sa.Column("tutee_login", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("personal_tutoring_meeting", "timestamp")
    op.drop_column("personal_tutoring_meeting", "tutor")
    op.drop_column("personal_tutoring_meeting", "tutee")
    # ### end Alembic commands ###
