"""Add tables for internal modules

Revision ID: a5085ad0c4f9
Revises: 2c46654e82f6
Create Date: 2024-03-19 12:29:58.043042

"""
import sqlalchemy as sa
import sqlmodel  # added
from alembic import op

# revision identifiers, used by Alembic.
revision = "a5085ad0c4f9"
down_revision = "2c46654e82f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "internal_module_on_offer",
        sa.Column("terms", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cohort_regulations",
        sa.Column(
            "offering_group",
            sa.Enum("OPTIONAL", "SELECTIVE", name="offering_group"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cohort", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ects", sa.Integer(), nullable=False),
        sa.Column("exam_component", sa.Integer(), nullable=False),
        sa.Column("cw_component", sa.Integer(), nullable=False),
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["module_id"],
            ["internal_module_on_offer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cohort_regulations_module_id"),
        "cohort_regulations",
        ["module_id"],
        unique=False,
    )
    op.create_table(
        "internal_module_choice",
        sa.Column(
            "timestamp",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cohort_regulations_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cohort_regulations_id"],
            ["cohort_regulations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cohort_regulations_id", "username"),
    )
    op.create_index(
        op.f("ix_internal_module_choice_cohort_regulations_id"),
        "internal_module_choice",
        ["cohort_regulations_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_internal_module_choice_cohort_regulations_id"),
        table_name="internal_module_choice",
    )
    op.drop_table("internal_module_choice")
    op.drop_index(
        op.f("ix_cohort_regulations_module_id"), table_name="cohort_regulations"
    )
    op.drop_table("cohort_regulations")
    op.drop_table("internal_module_on_offer")
    # ### end Alembic commands ###
