"""Drop configuration.degree_year

Revision ID: b4037303e321
Revises: b6caf360950b
Create Date: 2024-02-26 12:13:43.333162

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b4037303e321"
down_revision = "b6caf360950b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "configuration_degree_year_year_key", "configuration", type_="unique"
    )
    op.create_unique_constraint(None, "configuration", ["year"])
    op.drop_column("configuration", "degree_year")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "configuration",
        sa.Column("degree_year", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "configuration", type_="unique")
    op.create_unique_constraint(
        "configuration_degree_year_year_key", "configuration", ["degree_year", "year"]
    )
    # ### end Alembic commands ###
