"""Initial migration

Revision ID: b6caf360950b
Revises:
Create Date: 2024-02-16 20:42:52.400067

"""
import sqlalchemy as sa
import sqlmodel  # added
from alembic import op

# revision identifiers, used by Alembic.
revision = "b6caf360950b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "configuration",
        sa.Column(
            "status",
            sa.Enum("OPEN", "CLOSED", "USE_PERIODS", name="module_selection_status"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("degree_year", sa.Integer(), nullable=False),
        sa.Column("year", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("degree_year", "year"),
    )
    op.create_table(
        "enrolment",
        sa.Column(
            "timestamp",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "student_username",
            sqlmodel.sql.sqltypes.AutoString(length=10),
            nullable=False,
        ),
        sa.Column("enrolment_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("module_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("year", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "selection_period",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start", sa.DateTime(), nullable=False),
        sa.Column("end", sa.DateTime(), nullable=False),
        sa.Column("configuration_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["configuration_id"],
            ["configuration.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("selection_period")
    op.drop_table("enrolment")
    op.drop_table("configuration")
    # ### end Alembic commands ###
