"""Drop table enrolment

Revision ID: bcf82183391a
Revises: a5085ad0c4f9
Create Date: 2024-03-22 15:32:08.605758

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "bcf82183391a"
down_revision = "a5085ad0c4f9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("enrolment")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "enrolment",
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(),
            server_default=sa.text("timezone('UTC'::text, CURRENT_TIMESTAMP)"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "student_username",
            sa.VARCHAR(length=10),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("enrolment_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("module_code", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("year", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="enrolment_pkey"),
    )
    # ### end Alembic commands ###
