"""Establish relation between cohort_regulations and offering_group

Revision ID: c41c1e8b2829
Revises: 0b3983590c8d
Create Date: 2024-03-26 15:10:25.479548

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c41c1e8b2829"
down_revision = "0b3983590c8d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cohort_regulations",
        sa.Column("offering_group_id", sa.Integer(), nullable=False),
    )
    op.create_foreign_key(
        None, "cohort_regulations", "offering_group", ["offering_group_id"], ["id"]
    )
    op.drop_column("cohort_regulations", "offering_group")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cohort_regulations",
        sa.Column(
            "offering_group",
            postgresql.ENUM("OPTIONAL", "SELECTIVE", name="offering_group_label"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "cohort_regulations", type_="foreignkey")
    op.drop_column("cohort_regulations", "offering_group_id")
    # ### end Alembic commands ###
