"""add external module on offer table

Revision ID: c6ede63a2345
Revises: ec8f361d0e5f
Create Date: 2024-03-05 16:44:53.453170

"""
import sqlalchemy as sa
import sqlmodel  # added
from alembic import op

# revision identifiers, used by Alembic.
revision = "c6ede63a2345"
down_revision = "ec8f361d0e5f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "external_module_on_offer",
        sa.Column("terms", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
        sa.Column("ects", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("external_module_on_offer")
    # ### end Alembic commands ###
