"""Add personal tutoring meeting table

Revision ID: e5dde5f23626
Revises: ac8e46fdb666
Create Date: 2023-09-06 14:49:43.325025

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "e5dde5f23626"
down_revision = "ac8e46fdb666"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "personal_tutoring_meeting",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("meeting_date", sa.Date(), nullable=False),
        sa.Column("tutee_login", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tutor_login", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("personal_tutoring_meeting")
    # ### end Alembic commands ###
