"""Add external_module_choice table

Revision ID: ec8f361d0e5f
Revises: f4a4ab5d6296
Create Date: 2024-02-26 19:43:02.449162

"""
import sqlalchemy as sa
import sqlmodel  # added
from alembic import op

# revision identifiers, used by Alembic.
revision = "ec8f361d0e5f"
down_revision = "f4a4ab5d6296"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "external_module_choice",
        sa.Column(
            "timestamp",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "APPROVED", "REJECTED", "PENDING", name="module_choice_approval_status"
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("module_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reviewed_on", sa.DateTime(), nullable=True),
        sa.Column("reviewed_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("year", "module_code", "username"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("external_module_choice")
    # ### end Alembic commands ###
