name: Trigger auto deployment for moduleselection

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/moduleSelection-AutoDeployTrigger-40869bd2-733f-4468-93ff-6550eacc47e2.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MODULESELECTION_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.MODULESELECTION_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MODULESELECTION_REGISTRY_PASSWORD }}
          containerAppName: moduleselection
          resourceGroup: brady
          imageToBuild: ghcr.io/moduleselection:${{ github.sha }}
          
            

     

