name: Trigger auto deployment for moduleselection

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/moduleSelection-AutoDeployTrigger-40869bd2-733f-4468-93ff-6550eacc47e2.yml'

  # Allow manual trigger 
  workflow_dispatch:

defaults:
  run:
    # GitHub Actions run without a TTY device. This is a workaround to get one,
    # based on https://github.com/actions/runner/issues/241#issuecomment-2019042651
    shell: 'script --return --quiet --log-out /dev/null --command "bash -e {0}"'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MODULESELECTION_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.MODULESELECTION_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MODULESELECTION_REGISTRY_PASSWORD }}
          containerAppName: moduleselection
          resourceGroup: brady
          imageToBuild: ghcr.io/doc-scientia/moduleselection:${{ github.sha }}
  
  check-deployment:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.MODULESELECTION_AZURE_CREDENTIALS }}
    - name: Validate deployment succeeded
      run: |
        while true; do
            output=$(az containerapp revision list -n moduleselection -g brady --query "[].properties.[healthState,provisioningState]" -o table)
            if echo "$output" | grep -q None; then
                sleep 1
            else
                break
            fi
        done

        if echo "$output" | grep -E "Unhealthy|Failed"; then
            echo "App failed to deploy"
            exit 1
        else
            echo "App deployed successfully"
        fi

  run-migrations:
    runs-on: ubuntu-latest
    needs: check-deployment
    
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.MODULESELECTION_AZURE_CREDENTIALS }}
    - name: alembic upgrade head
      run: >
        /usr/bin/az containerapp exec
          --name "moduleselection"
          --resource-group "brady"
          --command "alembic upgrade head"
